# Generated by Django 4.2.2 on 2023-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohrana', '0002_remove_my_incid_content_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_incid',
            name='content_6',
            field=models.TextField(blank=True),
        ),
    ]
