# Generated by Django 4.2.2 on 2023-07-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohrana', '0003_my_incid_content_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_incid',
            old_name='is_published',
            new_name='is_publishe',
        ),
        migrations.RenameField(
            model_name='my_incid',
            old_name='time_create',
            new_name='time_creat',
        ),
        migrations.RenameField(
            model_name='my_incid',
            old_name='time_update',
            new_name='time_updat',
        ),
    ]
