# Generated by Django 4.2.2 on 2023-07-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohrana', '0004_rename_is_published_my_incid_is_publishe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_incid',
            old_name='is_publishe',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='my_incid',
            old_name='time_creat',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='my_incid',
            old_name='time_updat',
            new_name='time_update',
        ),
    ]
