# Generated by Django 4.2.2 on 2023-07-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohrana', '0005_rename_is_publishe_my_incid_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_incid',
            name='content_6',
        ),
    ]
